version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-enaa
    environment:
      MYSQL_DATABASE: competencedata
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: spring-enaa
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/competencedata
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  db-data:
